---
title: "Base Maps"
author: "Camila Vargas"
date: "8/21/2018"
output: html_document
---

This Script plys round with how to add a base map to the geojason EEZ files of each OHI region.

##Trying to add a base map to Aruba and Chile

```{r}
#setwd('~/Desktop/Camila')

##Load libraries

library(parallel)
library(doParallel)
library(rgdal)
library(raster)
library(sf)
library(ggplot2)
library(tidyverse)
library(raster)


abw <- sf::st_read("https://raw.githubusercontent.com/OHI-Science/ohi-webapps/master/ohi_gadm_geojson_archive/regions_gcs_abw.geojson") %>% 
  dplyr::select(-rgn_nam) %>% 
  st_combine()

plot(abw)

ggplot(abw) 


chl <- sf::st_read("https://raw.githubusercontent.com/OHI-Science/ohi-webapps/master/ohi_gadm_geojson_archive/regions_gcs_chl.geojson") %>% 
  dplyr::select(-rgn_nam)   #list of names of geopolitical regions of chile
  
#st_cast("POLYGON")
  
  #sf::st_combine()

## functions I have tried and don't work
## st_cast()


chl_2chl <- sf::st_read("https://raw.githubusercontent.com/OHI-Science/ohi-webapps/master/ohi_gadm_geojson_archive/regions_gcs_chl.geojson") %>% 
  dplyr::select(-rgn_nam) 


plot(chl)

chl_map <- ggplot()+
  geom_sf(data = chl, color = "gray30", fill = NA)


## Using ggmaps

library(ggmap)

abw_loc <- c(-69.87874, 13.78236) ## Approach one ginving the long, lat of the center point of the bbox (calculated below)

abw_map <- get_map(location = abw_loc, zoom = 8, source = "google", maptype = "terrain", crop = FALSE)
ggmap(abw_map)

## center point of aruba bbox
##Lon
((-70.41667--69.34081)/2) #=-0.53793

-70.41667 - 0.53793 #=-70.9546

-70.41667 + 0.53793 # = -69.87874

##Lat
((15.41333- 12.15139)/2) # =1.63097
12.15139+1.63097 # =13.78236

## Second approach using the bbox coordnates and zoom

abw_loc_2 <- c(-70.41667,12.15139, -69.34081, 15.41333) 

abw_map_2 <- get_map(location = abw_loc, zoom = 8, source = "google", maptype = "terrain", crop = FALSE)
ggmap(abw_map_2)


## ggmaps and sf

## My sf shapefile
abw # ESPG 4326

##map
abw_map_2

##Combining both! It works!!!
st_crs(abw_map_2)
plot(st_transform(abw, crs = 3857)[1], bgMap = abw_map_2)


##Chile
chl

##bbox
##bbox: xmin: -113.2038 ymin: -59.8649 xmax: -65.72667 ymax: -18.35102

## note for how to set locations:  lowerleftlon(xmin), lowerleftlat (ymin), upperrightlon (xmax), upperrightlat (ymax)
chl_loc <- c(-113.2038, -59.8649, -65.72667, -18.35102)
chl_map <- get_map(location = chl_loc, zoom = 3, source = "google", maptype = "terrain", crop = FALSE)
ggmap(chl_map)

#overlap
st_crs(chl_map)
plot(st_transform(chl, crs = 3857)[1], bgMap = chl_map)

plot(st_transform(chl, crs = 3857), bgMap = chl_map)


```


Combining polygons

```{r}
## Exmaple code. This is what I want to do to my multipolygon figure.

library(sf)
library(sp)
library(rgeos)

clusterSF <- function(sfpolys, thresh){
    dmat = st_distance(sfpolys)
    hc = hclust(as.dist(dmat>thresh), method="single")
    groups = cutree(hc, h=0.5)
    d = st_sf(
        geom = do.call(c,
            lapply(1:max(groups), function(g){
                st_union(sfpolys[groups==g,])
            })
            )
        )
    d$group = 1:nrow(d)
    d
}

set.seed(123)
pols  = st_as_sf(
    gBuffer(SpatialPoints(cbind(100*runif(20),100*runif(20))), width=12, byid=TRUE)
)

plot(pols)

polcluster = clusterSF(pols, 1)

plot(polcluster, col=polcluster$group)


##trying with chile!

chl_cluster <- clusterSF(chl, 1)



```


Exploring a second option for EEZ maps witht he low_res files

```{r}

library(readOGR)
library(leaflet)

all_rgns <- sf::st_read('../ohiprep/globalprep/spatial/downres', layer="rgn_all_gcs_low_res") %>%
  dplyr::filter(rgn_typ == "eez") %>% 
  dplyr::select(rgn_id, rgn_key, geometry)
  

chl_lr <- all_rgns %>% 
  filter(rgn_id== 224) %>% 
  `st_crs<-`(3857) ##adds coordenate reference system

##Making the poligon valid

library(lwgeom)
chl_valid <- st_make_valid(chl_lr)

plot(chl_valid)


##back to ggmap
chl_loc <- c(-113.2038, -59.8649, -65.72667, -18.35102)

chl_map <- get_map(location = chl_loc, zoom = 3, source = "google", maptype = "terrain", crop = FALSE)
ggmap(chl_map)


#overlap with plot function --> not working. no overlap
st_crs(chl_map)
plot(chl_valid[1], bgMap = chl_map)
plot(st_transform(chl_valid, crs = 3857)[1], bgMap = chl_map)

## overlap with ggplot


# Define a function to fix the bbox to be in EPSG:3857
ggmap_bbox <- function(map) { #map = chl_map
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))

  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))

  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}

# Use the function:
map <- ggmap_bbox(map)

ggmap(map) + 
  coord_sf(crs = st_crs(3857)) + # force the ggplot2 map to be in 3857
  geom_sf(data= chl_valid, color= "gray30", fill= NA)

ggplot(map)+
geom_sf(data = chl_valid, color = "gray30", fill = NA)+









```


## Extras

```{r}
## cool leafet

rgns_leaflet <- all_rgns %>%
  filter(rgn_typ == "eez")

##Plot all reagions eez polygons in leaflet
leaflet(rgns_leaflet) %>% addPolygons()

##Plot chile eez polygon in leaflet
leaflet(chl_lr) %>% addPolygons()



##Base map with laeflet

chl_base <- leaflet() %>% addTiles() %>% 
  fitBounds(-113.1767, -59.83022, -65.72667, -18.35222)

chl_base



```




